# Generated by Django 3.1.3 on 2021-09-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20210907_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
