# Generated by Django 3.1.3 on 2021-09-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_auto_20210918_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
