# Generated by Django 3.1.3 on 2021-09-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_remove_profile_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
