# Generated by Django 3.1.3 on 2021-09-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_notice',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
